services:
  - type: worker
    name: fq-bot
    runtime: python
    buildCommand: apt-get update && apt-get install -y ffmpeg wget unzip && pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false

  - type: web
    name: fq-bot-web
    runtime: python
    buildCommand: pip install flask gunicorn
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_PATH
        value: /secret-tools
      - key: MINI_APP_URL
        sync: false
